### ISSUE TITLE
How to disable 'typing sound'?

### ISSUE THREAD

**Issue by annadapb** [borisfaure/terminology#100]
When I type anything, I can hear the sound of keys hitting like I'm typing on a IBM Model M bucklespring. I am sure this sound is not coming physically from my keyboard. I put my ears to it. But it sure is coming from my speakers. And this sound comes when I type on terminology. No sound when I type on my web browser or mate-terminal.

The sound also happens when I set terminology to use 'Blinking Underline' as my default cursor. I want to turn off this sound. How can I turn it off? I searched thorough I couldn't find anything I understand.

**Comment by borisfaure** [comment]
You can disable it using the following:

1. Right click to show the Controls panel
2. Settings
3. Behaviour
4. Untick `React to key presses`

Great choice of keyboard!
