### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by SL-Pirate** [borisfaure/terminology#106]
I have a linux mint 20.1 cinnamon.
I can't drag and drop files into the terminal to get their absolute path. Instead I have to copy and paste the file.
This feature used to work in GNOME terminal and I miss it a lot.
I don't know if terminology is lacking the feature or something is wrong. Please help me to figure this out.
Thank you

![image](https://user-images.githubusercontent.com/80326180/124348166-06fb9e80-dc06-11eb-9099-6c0002d6d085.png)

**Comment by SL-Pirate** [comment]
And there's another problem that when I preview a video using tycat, the playback has issues. I don't know exactly what it's (maybe a CODEC issue) but every video I preview shows only some green lines. I still can hear the sound.

**Comment by chilledsaint0716** [comment]
I have the same problem in Ubuntu 20.04LTS lol.

**Comment by borisfaure** [comment]
Should be fixed with commit 5f10cb1857ada8d29a21579814ad600ed6d0ca12
