### ISSUE TITLE
How do  you use Terminology on framebuffer?

### ISSUE THREAD

**Issue by DirtyVoid** [borisfaure/terminology#131]
I use terminology for everything on my desktop environment. But I have seen on the website that you can use it on login at tty. but it does not work with frame buffer and fails to run. If it does not come with instruction how you can run it on framebuffer how can a normal person like me use it? (using it on void linux)

**Comment by borisfaure** [comment]
You need to set the following as environment variables:

- `ELM_DISPLAY=fb`
- `ELM_ACCEL=none`
- `EVAS_FB_DEV=/dev/fb0`

Please note that I haven't used this in ages

**Comment by borisfaure** [comment]
Added those to the readme.

**Comment by DirtyVoid** [comment]
Thanks.
