### ISSUE TITLE
Do not show new colorschemes

### ISSUE THREAD

**Issue by nagini9** [borisfaure/terminology#133]
After following the instructions and executing the following command:
`./add_color_scheme.sh eet ~/.config/terminology/colorschemes/test.eet test.ini`

The new colorscheme does not appear in the color list
:(

[Installed libeet-bin, and colorschemes name was changed]

**Comment by 530f6caa** [comment]
I can confirm this bug, using Terminology built from the latest git sources. For me, the colorscheme can still be used by specifying the `--colorscheme` commandline option, even though it does not appear in the list. If the colorscheme is added to `colorschemes` in `data/colorschemes/meson.build` and Terminology is rebuilt and reinstalled, then the new colorscheme will show up, but I don't know what steps are necessary to make it show up without a rebuild and reinstall.

**Comment by borisfaure** [comment]
I have tested and it worked for me (no need to be root, just as my normal user):
```
cd data/colorschemes
cp Smyck.ini FooBar.ini
# edit the Metadata part in FooBar.ini
./add_color_scheme.sh eet ~/.config/terminology/colorschemes/FooBar.eet FooBar.ini
```
Start a new terminology (use `-s` to be sure it's a new instance) and I can see the FooBar color scheme in the list.

**Comment by 530f6caa** [comment]
> I have tested and it worked for me (no need to be root, just as my normal user):

You are correct, this does in fact behave as expected when actually running the latest version. It turns out that I still had a terminology process from my distribution's package running (where the bug is present), and I had Behavior -> Multiple instances, one process set to true while I was testing this.

(For reference, the package where the bug is present is terminology_1.12.1-1 from Ubuntu.)

**Comment by prosoitos** [comment]
I am having the same problem with version 1.13.0-1 on Arch Linux.

I tried the solution mentioned above of using `--colorscheme`, but that doesn't work either:

```
ERR<4218>:terminology ../src/bin/colors.c:713 _color_scheme_get() failed find colorscheme
```
