### ISSUE TITLE
Able to adjust background fade from settings page

### ISSUE THREAD

**Issue by mainlyetcetera** [borisfaure/terminology#138]
Hey Boris. I was in the efl chat channel, and you were helping me get the background darkened to make it easier to use images! Overall, that's going great! I did need to adjust my colors some, and needed to restart Terminology after changing colors before it liked the new background color, but other than that, good improvement!

I am wondering, if in the future, we can adjust how dark we can make the background from the settings page.

Thanks for all your help!

**Comment by borisfaure** [comment]
Hi Eric!
I made changes yesterday to make that easier. I was cheering and wanted to make you some screenshots of the feature but it's not working as great as I want.
The idea is that under the Background panel, the fading slider is always active and would let you adjust the fading between the background image and the background color from the chosen color scheme.

**Comment by mainlyetcetera** [comment]
Well, absolutely no rush! I look forward to this! :)

**Comment by borisfaure** [comment]
This is done in f7e38a19ad06a836fa1c466805db4cb2da09b767

**Comment by borisfaure** [comment]
![terminology_background_opacity_01](https://user-images.githubusercontent.com/27988/195199295-a8d7c4d3-4e1a-4e29-9671-0b61cb4630b8.png)
![terminology_background_opacity_02](https://user-images.githubusercontent.com/27988/195199301-c4acb0a4-7266-4353-bc35-16493ee620c1.png)
![terminology_background_opacity_03](https://user-images.githubusercontent.com/27988/195199303-a10e6544-fbf0-4dc9-ab8f-29bbaea433bd.png)
![terminology_background_opacity_04](https://user-images.githubusercontent.com/27988/195199305-5daf3246-8bb0-4097-ab04-237e57d1d98c.png)
![terminology_background_opacity_05](https://user-images.githubusercontent.com/27988/195199307-1cb81418-364a-4c39-964a-41814dec4ab8.png)
![terminology_background_opacity_06](https://user-images.githubusercontent.com/27988/195199309-58ef7f27-c918-4819-b9c7-c17afa558da6.png)
![terminology_background_opacity_07](https://user-images.githubusercontent.com/27988/195199310-59efe4b9-1830-443b-81e7-37c3d5a43231.png)
![terminology_background_opacity_08](https://user-images.githubusercontent.com/27988/195199313-fb3429a7-5cfb-4b93-bb38-1508eb839b12.png)
![terminology_background_opacity_09](https://user-images.githubusercontent.com/27988/195199316-b893d45b-9d7b-4ae2-be06-8cd256f3c72d.png)

**Comment by mainlyetcetera** [comment]
Yep, that's what I'm seeing, too! Thanks a ton, @borisfaure!
