### ISSUE TITLE
Keyboard always in qwerty?

### ISSUE THREAD

**Issue by defdefred** [borisfaure/terminology#159]
Hello,

Terminology on framebuffer is wonderfull and very usefull for a lot of old computer or small SBC.
Vim with italic from the console is a must!

I have only one little trouble... the keyboard is not following my configuration. It is always in `qwerty`.
```
System Locale: LANG=fr_FR.UTF-8
               LANGUAGE=fr_FR
    VC Keymap: (unset)
   X11 Layout: fr
    X11 Model: pc105
  X11 Variant: azerty
  X11 Options: lv3:ralt_switch,compose:rwin
```
Any idea what's wrong with me?

**Comment by defdefred** [comment]
Master GIT is https://git.enlightenment.org/enlightenment/terminology/issues/10

**Comment by borisfaure** [comment]
It's not supported in `ecore_evas`.
