### ISSUE TITLE
could not save colorscheme setting if .eet filename is different from metadata name

### ISSUE THREAD

**Issue by zerobikappa** [borisfaure/terminology#162]
https://github.com/borisfaure/terminology/blob/bbcedcb95f09e8136dc6dea702e22fe617a318e5/data/colorschemes/Fir%20Dark.ini#L11

If I select "Dark Fir" as colorscheme, when I launch terminology next time the colorscheme would reset to "Default".
Also failed to set colorscheme using `terminology --colorscheme="Dark Fir"` or `terminology --colorscheme="Fir Dark"`

**Comment by spectrum70** [comment]
i have the same issue

**Comment by borisfaure** [comment]
Thanks for noticing it again. I forgot about that one. Sorry
