### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by NotMizzel** [borisfaure/terminology#165]
I installed terminology and accidentally set the scale to 5, and I can't edit the scale from the GUI, so I have to find another way.
![image](https://user-images.githubusercontent.com/113567858/230698339-ad51d7e0-e26e-4783-80d6-c6a8b38b8580.png)

**Comment by borisfaure** [comment]
You can run `terminology --scale=1.0` and then change the scale in the UI

**Comment by NotMizzel** [comment]
Thank you so much, I haven't found a way to do this but now I know.
