### ISSUE TITLE
settings, icons not visible, except for mouse

### ISSUE THREAD

**Issue by spectrum70** [borisfaure/terminology#170]
from arch official repo, i have installed 

extra/terminology 1.13.0-1 [installed]

https://snipboard.io/YoFmjW.jpg

Going on "Controls", no icons are visible, going on settings, only
mouse icon is visible.

**Comment by borisfaure** [comment]
This should be handle by the `efl` package.

**Comment by borisfaure** [comment]
Could you please try to run `elementary_config` and change the icons settings?

**Comment by spectrum70** [comment]
efl package is already installed.
Yes, elementary_config solved, i set " use elementary icons" and all is ok now.

Thanks
