### ISSUE TITLE
Title bar disappears when setting any translucency

### ISSUE THREAD

**Issue by fexofenadine** [borisfaure/terminology#73]
Using XFCE (GalliumOS), if I set the translucency checkbox to on/checked, the title bar of the terminal window disappears. It isn't invisible, as I can click the window behind through the space that the bar should occupy. Toggling translucency off again brings it back immediately. Not having the bar means the window isn't moveable or minimise-able.

Doesn't seem to matter how translucent it is, any setting removes the title bar.

Happy to provide more information if required

**Comment by borisfaure** [comment]
Are you using wayland?
Do you have `elementary_test`? If so, can you search for `window states` and click on the button. That should produce with some button. If you then click on `Alpha On`, do you have the same issue?
