### ISSUE TITLE
--hold -e "echo ------" doesn't print anything

### ISSUE THREAD

**Issue by abitrolly** [borisfaure/terminology#78]
This opens a new window with no output.
```bash
terminology --hold -e "echo ---------------"
```
However, appending the `;bash` make it work.
```bash
terminology --hold -e "echo ---------------;bash"
```
![image](https://user-images.githubusercontent.com/8781107/100365841-0ddb8680-3011-11eb-9dc7-1ce2d6d8af89.png)

**Comment by borisfaure** [comment]
Thank you for your patience.
I think it can not be solved because the pseudo terminal device (see `man pty`) is closed once the command exit, even before reading any input it could have written.

**Comment by abitrolly** [comment]
@borisfaure does that mean `--hold` is a no op? Why Terminology can not spawn child process that will `--hold` the `pty` until it is no longer needed?

This bug makes it harder to manage window sessions with Terminology. One need to make sure to append bash to every command to see the results.
