### ISSUE TITLE
Difficulties to launch on nvidia propertiary UEFI driver

### ISSUE THREAD

**Issue by japiotr123** [borisfaure/terminology#79]
Hi
I have uefi pc with nvidia gpu, when i try to run this program on tty  without nvidia's kms, i getting many errors.https://hastebin.com/aziyocepot
when i try to run with nvidia modeset, my computer freezes, and only power button works. can i do something to run it on nvidia kms?

**Comment by borisfaure** [comment]
How do you run it exactly?

**Comment by japiotr123** [comment]
I run it with a command `terminology` in tty, on my lenovo laptop it works perfectly
I using Artix linux (arch without systemd)
[yaft](https://github.com/uobikiemukot/yaft) works perfectly on my desktop

**Comment by japiotr123** [comment]
when I using `export ELM_ENGINE=fb` this works, but mouse and keyboard not works

**Comment by japiotr123** [comment]
on nouveau it works perfectly , without ELM_ENGINE variable, keyboard and mouse works too

**Comment by japiotr123** [comment]
my motherboard is ASUS prime z270-a
graphics is MSI gtx 1060 3GB

**Comment by japiotr123** [comment]
this problem is exists only in default drm mode, when i set ELM_ENGINE=fb, it works

**Comment by borisfaure** [comment]
Based on your testing, it seems like the issue is with nvidia's drm code itself.
You edited your comments, but do you know with drm on nouveau? That would point the issue to nvidia.
