### ISSUE TITLE
Text formatted with ansi escape codes isn't rendered

### ISSUE THREAD

**Issue by Michael-F-Bryan** [borisfaure/terminology#95]
Some text, notably anything styled like the notes in `rustc`'s *"mismatched type"* error message, doesn't get rendered by the Terminology terminal emulator.

For example, here is an error message as shown in `xterm`:

![DeepinScreenshot_select-area_20210225114435](https://user-images.githubusercontent.com/17380079/109100888-adb7c600-7760-11eb-9c00-4f80d8e8e836.png)

And this is what I see in `terminology`:

![DeepinScreenshot_select-area_20210225113802](https://user-images.githubusercontent.com/17380079/109100903-b4ded400-7760-11eb-8713-ed7cecd6520c.png)

Output including ascii escape codes: [out.txt](https://github.com/BurntSushi/termcolor/files/6040401/out.txt)

You'll notice that there are no *"expected `f32`, found `&f32`"* notes.

This doesn't seem to be an issue with the text blending into the background because if I change background colours it still won't appear. I've also copy-paste'd the output into a text editor and it looks like the red notes never even make its way to the terminal's output.

**Comment by borisfaure** [comment]
I should have replied sooner…
I'm also doing some rust from time to time and I never noticed this. Could you please try with an other color scheme?
Which version are you using?

**Comment by Michael-F-Bryan** [comment]
I would have been using the latest version version in the Arch repositories at the time I made the ticket.

I've since switched over to alacritty and uninstalled terminology so can't easily check.
