### ISSUE TITLE
Autoselect Emoji Color Font?

### ISSUE THREAD

**Issue by kdato** [borisfaure/terminology#98]
I use "Courier (Regular)" as my terminal font, which only displays black and white emoji in terminology-1.9.0. I have to select "Noto Color Emoji (Regular)" manually to see color emoji.

Is  there a way to make terminology select color emojis alongside my regular font? The terminal I used previously, kitty, did it.

Thanks folks.

kdato

**Comment by borisfaure** [comment]
Terminology uses Fontconfig.
